# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-07 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.IntegerField(null=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
