# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-07 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20180907_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderDetail',
            new_name='OrderDetail',
        ),
    ]
