# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-07 03:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.IntegerField(null=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('import_price', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.Category')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
